/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AuthPassword: typeof import('./src/components/auth/password.vue')['default']
    AuthWechat: typeof import('./src/components/auth/wechat.vue')['default']
    Bimgo: typeof import('./src/components/Bimgo.vue')['default']
    Button: typeof import('./src/shadcn/ui/button/Button.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Toast: typeof import('./src/shadcn/ui/toast/Toast.vue')['default']
    ToastAction: typeof import('./src/shadcn/ui/toast/ToastAction.vue')['default']
    ToastClose: typeof import('./src/shadcn/ui/toast/ToastClose.vue')['default']
    ToastDescription: typeof import('./src/shadcn/ui/toast/ToastDescription.vue')['default']
    Toaster: typeof import('./src/shadcn/ui/toast/Toaster.vue')['default']
    ToastProvider: typeof import('./src/shadcn/ui/toast/ToastProvider.vue')['default']
    ToastTitle: typeof import('./src/shadcn/ui/toast/ToastTitle.vue')['default']
    ToastViewport: typeof import('./src/shadcn/ui/toast/ToastViewport.vue')['default']
  }
}
