/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AuthPassword: typeof import('./src/components/auth/password.vue')['default']
    AuthWechat: typeof import('./src/components/auth/wechat.vue')['default']
    Bimgo: typeof import('./src/components/Bimgo.vue')['default']
    Button: typeof import('./src/shadcn/ui/button/Button.vue')['default']
    CountDown: typeof import('./src/components/countDown.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElLink: typeof import('element-plus/es')['ElLink']
    ElScrollbar: typeof import('element-plus/es')['ElScrollbar']
    FormControl: typeof import('./src/shadcn/ui/form/FormControl.vue')['default']
    FormDescription: typeof import('./src/shadcn/ui/form/FormDescription.vue')['default']
    FormItem: typeof import('./src/shadcn/ui/form/FormItem.vue')['default']
    FormLabel: typeof import('./src/shadcn/ui/form/FormLabel.vue')['default']
    FormMessage: typeof import('./src/shadcn/ui/form/FormMessage.vue')['default']
    Input: typeof import('./src/shadcn/ui/input/Input.vue')['default']
    Label: typeof import('./src/shadcn/ui/label/Label.vue')['default']
    Loading: typeof import('./src/components/Loading.vue')['default']
    Logo: typeof import('./src/components/Logo.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SearchButton: typeof import('./src/components/search/button.vue')['default']
    Sidebar: typeof import('./src/components/sidebar/index.vue')['default']
    Toast: typeof import('./src/shadcn/ui/toast/Toast.vue')['default']
    ToastAction: typeof import('./src/shadcn/ui/toast/ToastAction.vue')['default']
    ToastClose: typeof import('./src/shadcn/ui/toast/ToastClose.vue')['default']
    ToastDescription: typeof import('./src/shadcn/ui/toast/ToastDescription.vue')['default']
    Toaster: typeof import('./src/shadcn/ui/toast/Toaster.vue')['default']
    ToastProvider: typeof import('./src/shadcn/ui/toast/ToastProvider.vue')['default']
    ToastTitle: typeof import('./src/shadcn/ui/toast/ToastTitle.vue')['default']
    ToastViewport: typeof import('./src/shadcn/ui/toast/ToastViewport.vue')['default']
  }
}
